import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Navbar from '@/components/Navbar'
import SideLinks from '@/components/SideLinks'
import FollowCursorCircle from '@/components/Cursor'
import ToTopButton from '@/components/ToTop'

const inter = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
          >
            {/* <FollowCursorCircle /> */}
            <Navbar />
            <SideLinks />
            <ToTopButton />
            {children}
          </ThemeProvider>
        </body>
      </html>
  )
}
